services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: enterprise_rest_api
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d enterprise_rest_api"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - enterprise-rest-api-postgres:/var/lib/postgresql/data

volumes:
  enterprise-rest-api-postgres:
